# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import refinerycalc
from refinerycalc.api.weather_forecast_api import WeatherForecastApi  # noqa: E501
from refinerycalc.rest import ApiException


class TestWeatherForecastApi(unittest.TestCase):
    """WeatherForecastApi unit test stubs"""

    def setUp(self):
        self.api = WeatherForecastApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_weather_forecast(self):
        """Test case for get_weather_forecast

        """
        pass


if __name__ == '__main__':
    unittest.main()
