# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import refinerycalc
from refinerycalc.models.calculator_crude_price_mode_output_model import CalculatorCrudePriceModeOutputModel  # noqa: E501
from refinerycalc.rest import ApiException


class TestCalculatorCrudePriceModeOutputModel(unittest.TestCase):
    """CalculatorCrudePriceModeOutputModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCalculatorCrudePriceModeOutputModel(self):
        """Test CalculatorCrudePriceModeOutputModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = refinerycalc.models.calculator_crude_price_mode_output_model.CalculatorCrudePriceModeOutputModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
