# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import refinerycalc
from refinerycalc.api.crudes_api import CrudesApi  # noqa: E501
from refinerycalc.rest import ApiException


class TestCrudesApi(unittest.TestCase):
    """CrudesApi unit test stubs"""

    def setUp(self):
        self.api = CrudesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_crudes_get(self):
        """Test case for v1_crudes_get

        Get all crudes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
