# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CustomAggregateDetailModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'aggregate_name': 'str',
        'pricing_region': 'str',
        'default_crude_refinery': 'str',
        'refinery_year': 'int',
        'pricing_region_id': 'int',
        'default_crude_refinery_id': 'int',
        'refineries': 'list[CustomAggregateRefieryItemModel]'
    }

    attribute_map = {
        'id': 'id',
        'aggregate_name': 'aggregateName',
        'pricing_region': 'pricingRegion',
        'default_crude_refinery': 'defaultCrudeRefinery',
        'refinery_year': 'refineryYear',
        'pricing_region_id': 'pricingRegionId',
        'default_crude_refinery_id': 'defaultCrudeRefineryId',
        'refineries': 'refineries'
    }

    def __init__(self, id=None, aggregate_name=None, pricing_region=None, default_crude_refinery=None, refinery_year=None, pricing_region_id=None, default_crude_refinery_id=None, refineries=None):  # noqa: E501
        """CustomAggregateDetailModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._aggregate_name = None
        self._pricing_region = None
        self._default_crude_refinery = None
        self._refinery_year = None
        self._pricing_region_id = None
        self._default_crude_refinery_id = None
        self._refineries = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if aggregate_name is not None:
            self.aggregate_name = aggregate_name
        if pricing_region is not None:
            self.pricing_region = pricing_region
        if default_crude_refinery is not None:
            self.default_crude_refinery = default_crude_refinery
        if refinery_year is not None:
            self.refinery_year = refinery_year
        if pricing_region_id is not None:
            self.pricing_region_id = pricing_region_id
        if default_crude_refinery_id is not None:
            self.default_crude_refinery_id = default_crude_refinery_id
        if refineries is not None:
            self.refineries = refineries

    @property
    def id(self):
        """Gets the id of this CustomAggregateDetailModel.  # noqa: E501


        :return: The id of this CustomAggregateDetailModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CustomAggregateDetailModel.


        :param id: The id of this CustomAggregateDetailModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def aggregate_name(self):
        """Gets the aggregate_name of this CustomAggregateDetailModel.  # noqa: E501


        :return: The aggregate_name of this CustomAggregateDetailModel.  # noqa: E501
        :rtype: str
        """
        return self._aggregate_name

    @aggregate_name.setter
    def aggregate_name(self, aggregate_name):
        """Sets the aggregate_name of this CustomAggregateDetailModel.


        :param aggregate_name: The aggregate_name of this CustomAggregateDetailModel.  # noqa: E501
        :type: str
        """

        self._aggregate_name = aggregate_name

    @property
    def pricing_region(self):
        """Gets the pricing_region of this CustomAggregateDetailModel.  # noqa: E501


        :return: The pricing_region of this CustomAggregateDetailModel.  # noqa: E501
        :rtype: str
        """
        return self._pricing_region

    @pricing_region.setter
    def pricing_region(self, pricing_region):
        """Sets the pricing_region of this CustomAggregateDetailModel.


        :param pricing_region: The pricing_region of this CustomAggregateDetailModel.  # noqa: E501
        :type: str
        """

        self._pricing_region = pricing_region

    @property
    def default_crude_refinery(self):
        """Gets the default_crude_refinery of this CustomAggregateDetailModel.  # noqa: E501


        :return: The default_crude_refinery of this CustomAggregateDetailModel.  # noqa: E501
        :rtype: str
        """
        return self._default_crude_refinery

    @default_crude_refinery.setter
    def default_crude_refinery(self, default_crude_refinery):
        """Sets the default_crude_refinery of this CustomAggregateDetailModel.


        :param default_crude_refinery: The default_crude_refinery of this CustomAggregateDetailModel.  # noqa: E501
        :type: str
        """

        self._default_crude_refinery = default_crude_refinery

    @property
    def refinery_year(self):
        """Gets the refinery_year of this CustomAggregateDetailModel.  # noqa: E501


        :return: The refinery_year of this CustomAggregateDetailModel.  # noqa: E501
        :rtype: int
        """
        return self._refinery_year

    @refinery_year.setter
    def refinery_year(self, refinery_year):
        """Sets the refinery_year of this CustomAggregateDetailModel.


        :param refinery_year: The refinery_year of this CustomAggregateDetailModel.  # noqa: E501
        :type: int
        """

        self._refinery_year = refinery_year

    @property
    def pricing_region_id(self):
        """Gets the pricing_region_id of this CustomAggregateDetailModel.  # noqa: E501


        :return: The pricing_region_id of this CustomAggregateDetailModel.  # noqa: E501
        :rtype: int
        """
        return self._pricing_region_id

    @pricing_region_id.setter
    def pricing_region_id(self, pricing_region_id):
        """Sets the pricing_region_id of this CustomAggregateDetailModel.


        :param pricing_region_id: The pricing_region_id of this CustomAggregateDetailModel.  # noqa: E501
        :type: int
        """

        self._pricing_region_id = pricing_region_id

    @property
    def default_crude_refinery_id(self):
        """Gets the default_crude_refinery_id of this CustomAggregateDetailModel.  # noqa: E501


        :return: The default_crude_refinery_id of this CustomAggregateDetailModel.  # noqa: E501
        :rtype: int
        """
        return self._default_crude_refinery_id

    @default_crude_refinery_id.setter
    def default_crude_refinery_id(self, default_crude_refinery_id):
        """Sets the default_crude_refinery_id of this CustomAggregateDetailModel.


        :param default_crude_refinery_id: The default_crude_refinery_id of this CustomAggregateDetailModel.  # noqa: E501
        :type: int
        """

        self._default_crude_refinery_id = default_crude_refinery_id

    @property
    def refineries(self):
        """Gets the refineries of this CustomAggregateDetailModel.  # noqa: E501


        :return: The refineries of this CustomAggregateDetailModel.  # noqa: E501
        :rtype: list[CustomAggregateRefieryItemModel]
        """
        return self._refineries

    @refineries.setter
    def refineries(self, refineries):
        """Sets the refineries of this CustomAggregateDetailModel.


        :param refineries: The refineries of this CustomAggregateDetailModel.  # noqa: E501
        :type: list[CustomAggregateRefieryItemModel]
        """

        self._refineries = refineries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomAggregateDetailModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomAggregateDetailModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
