# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CustomAggregateRefieryItemModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'refinery_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'refinery_name': 'refineryName'
    }

    def __init__(self, id=None, refinery_name=None):  # noqa: E501
        """CustomAggregateRefieryItemModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._refinery_name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if refinery_name is not None:
            self.refinery_name = refinery_name

    @property
    def id(self):
        """Gets the id of this CustomAggregateRefieryItemModel.  # noqa: E501


        :return: The id of this CustomAggregateRefieryItemModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CustomAggregateRefieryItemModel.


        :param id: The id of this CustomAggregateRefieryItemModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def refinery_name(self):
        """Gets the refinery_name of this CustomAggregateRefieryItemModel.  # noqa: E501


        :return: The refinery_name of this CustomAggregateRefieryItemModel.  # noqa: E501
        :rtype: str
        """
        return self._refinery_name

    @refinery_name.setter
    def refinery_name(self, refinery_name):
        """Sets the refinery_name of this CustomAggregateRefieryItemModel.


        :param refinery_name: The refinery_name of this CustomAggregateRefieryItemModel.  # noqa: E501
        :type: str
        """

        self._refinery_name = refinery_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomAggregateRefieryItemModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomAggregateRefieryItemModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
