# coding: utf-8

"""
    Refinery Calc API Documentation

    Integrate the powerful Refinery Calc Engine into your process using this API.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@refinerycalc.com.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WeatherForecast(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'datetime',
        'temperature_c': 'int',
        'temperature_f': 'int',
        'summary': 'str'
    }

    attribute_map = {
        '_date': 'date',
        'temperature_c': 'temperatureC',
        'temperature_f': 'temperatureF',
        'summary': 'summary'
    }

    def __init__(self, _date=None, temperature_c=None, temperature_f=None, summary=None):  # noqa: E501
        """WeatherForecast - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._temperature_c = None
        self._temperature_f = None
        self._summary = None
        self.discriminator = None
        if _date is not None:
            self._date = _date
        if temperature_c is not None:
            self.temperature_c = temperature_c
        if temperature_f is not None:
            self.temperature_f = temperature_f
        if summary is not None:
            self.summary = summary

    @property
    def _date(self):
        """Gets the _date of this WeatherForecast.  # noqa: E501


        :return: The _date of this WeatherForecast.  # noqa: E501
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this WeatherForecast.


        :param _date: The _date of this WeatherForecast.  # noqa: E501
        :type: datetime
        """

        self.__date = _date

    @property
    def temperature_c(self):
        """Gets the temperature_c of this WeatherForecast.  # noqa: E501


        :return: The temperature_c of this WeatherForecast.  # noqa: E501
        :rtype: int
        """
        return self._temperature_c

    @temperature_c.setter
    def temperature_c(self, temperature_c):
        """Sets the temperature_c of this WeatherForecast.


        :param temperature_c: The temperature_c of this WeatherForecast.  # noqa: E501
        :type: int
        """

        self._temperature_c = temperature_c

    @property
    def temperature_f(self):
        """Gets the temperature_f of this WeatherForecast.  # noqa: E501


        :return: The temperature_f of this WeatherForecast.  # noqa: E501
        :rtype: int
        """
        return self._temperature_f

    @temperature_f.setter
    def temperature_f(self, temperature_f):
        """Sets the temperature_f of this WeatherForecast.


        :param temperature_f: The temperature_f of this WeatherForecast.  # noqa: E501
        :type: int
        """

        self._temperature_f = temperature_f

    @property
    def summary(self):
        """Gets the summary of this WeatherForecast.  # noqa: E501


        :return: The summary of this WeatherForecast.  # noqa: E501
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this WeatherForecast.


        :param summary: The summary of this WeatherForecast.  # noqa: E501
        :type: str
        """

        self._summary = summary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WeatherForecast, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WeatherForecast):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
